[tool.poetry]
name = "ons"
version = "0.2.1"
description = "UK Office for National Statistics (ONS) API Python interface"
authors = ["fzhulitov <fzhulitov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0.0"
requests = "*"
pandas = "^2.0.0"
importlib-metadata = "*"
lxml = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
