[tool.poetry]
name = "ons"
version = "1.0.1"
description = "UK Office for National Statistics (ONS) API Python interface"
authors = ["fzhulitov <fzhulitov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.14,<4.0.0"
requests = "*"
pandas = ">=2.0.0,<4.0.0"
importlib-metadata = "*"
lxml = "*"


[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
select = ["C", "E", "F", "W", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "ruff (>=0.15.14,<0.16.0)"
]
